### PR TITLE
set default value of datepickers in host request form as null 

### LINKED ISSUE #285: On request page, default dates should be empty (to force user input)
Hosts have been reporting to support that they sometimes receive requests with the incorrect dates for arrival and departure. This appears to be because the default arrival and departure dates are the current date and current date + 1. See  below:

image

To fix this:
1. The default dates should be empty
2. There should be a check to ensure the user inputs a date before they can submit the form.
3. If the user fails to enter in one of the dates or enters an invalid date, then an error text should appear below the date (either "required field" or "invalid date", depending on the error)

### PR DESCRIPTION
**Pull request by bakeiro**
Closes #285 

I think validation could use some improvements

What should be error feedback to users if they didn't select dates?

**Web frontend checklist**
- [x] Formatted my code with `make format`
- [x] There are no warnings from `make lint`
- [x] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

File: features/profile/view/NewHostRequest.tsx [hunk 1]
```diff
@@ -176,6 +177,7 @@ export default function NewHostRequest({
               id="from-date"
               label={t("profile:request_form.arrival_date")}
               name="fromDate"
+              defaultValue={null}
```
Comment (AndyMcGN) [inline features/profile/view/NewHostRequest.tsx:182]: I think it should be undefined, not null - I get this ts warning:
`Type 'null' is not assignable to type 'Dayjs | undefined'.ts(2322)
Datepicker.tsx(22, 3): The expected type comes from property 'defaultValue' which is declared here on type 'IntrinsicAttributes & DatepickerProps'`
Think it makes sense since it wasn't actively set to null, just hasn't been defined yet

File: features/profile/view/NewHostRequest.tsx [hunk 2]
```diff
@@ -86,14 +85,16 @@ export default function NewHostRequest({
   });
 
   useEffect(() => register("hostUserId"));
+  const empty_arrival_date = t("profile:request_form.arrival_date_empty");
```
Comment (AndyMcGN) [inline features/profile/view/NewHostRequest.tsx]: image
i get this error text when i try without a date, any idea what might be wrong?

Comment (AndyMcGN) [reply features/profile/view/NewHostRequest.tsx]: (`Error: request_form.arrival_date_empty`) in console

**Comment by AndyMcGN** [comment]
i think the feedback messages on errors are fine :) it's not displaying correctly for me.. could possibly be that i haven't got something set up right locally?

File: features/profile/view/NewHostRequest.tsx (hunk 2 above)
Comment (bakeiro) [reply features/profile/view/NewHostRequest.tsx]: that's weird... I'm gonna check it (do you have the changes in the file `features/profile/locales/en.json`?)

File: features/profile/view/NewHostRequest.tsx (hunk 1 above)
Comment (bakeiro) [reply features/profile/view/NewHostRequest.tsx:180]: hmm, I'm not getting this error (not Firefox neither Chrome)... are you copying the changes to your local branch? (instead of pulling the branch?)

Comment (bakeiro) [reply features/profile/view/NewHostRequest.tsx:182]: updated now :) (finally the bug was caused by the minDate prop)

Comment (AndyMcGN) [reply features/profile/view/NewHostRequest.tsx:182]: hmm sorry, i'm not sure why but when i look at it with undefined as the default value, it populates the field with today's date 😅 maybe null was the way to go!

Comment (bakeiro) [reply features/profile/view/NewHostRequest.tsx]: hmm, that's weird.. are you using the same branch as mine? (doesn't happen to me though)

**Comment by bakeiro** [comment]
changes done & app working correctly now

**Comment by bakeiro** [comment]
@AndyMcGN, @aapeliv, @darrenvong, @lucaslcode  review it if possible please :)

File: features/profile/view/NewHostRequest.tsx [hunk 3]
```diff
@@ -92,8 +91,21 @@ export default function NewHostRequest({
...
+        throw new Error(t("profile:request_form.arrival_date_empty"));
+      }
+
+      if (data.toDate === null) {
+        throw new Error(t("profile:request_form.departure_date_empty"));
+      }
+
+      if (data.text === "") {
+        throw new Error(t("profile:request_form.request_description_empty"));
+      }
```
Comment (darrenvong) [inline features/profile/view/NewHostRequest.tsx]: I think it'd be cleaner to utilise the [`rules` API offered by React Hook Form](https://legacy.react-hook-form.com/v6/api/#Controller) and perform the validation there instead of throwing errors like this.

Doing that way will also mean the error is displayed nearer the field where it occurs, which I think is a slightly nicer user experience than the fallback error banner at the top of the form.

There's an example of how we've done this in the past in the AccountForm that uses the date picker: https://github.com/Couchers-org/web-frontend/blob/eb8cc669e074d08de3c59bb0dc5f967c3d5be775/features/auth/signup/AccountForm.tsx#L198-L215

File: features/profile/view/NewHostRequest.tsx [hunk 4]
```diff
@@ -115,9 +129,13 @@ export default function NewHostRequest({
...
   useEffect(() => {
-    if (isSameOrFutureDate(watchFromDate, getValues("toDate"))) {
+    if (
+      watchFromDate &&
+      getValues("toDate") &&
+      isSameOrFutureDate(watchFromDate, getValues("toDate"))
+    ) {
       setValue("toDate", watchFromDate.add(1, "day"));
     }
   });
```
Comment (darrenvong) [inline features/profile/view/NewHostRequest.tsx:129]: Appreciate this is not code you've written (and it's been done a while ago!), but this `useEffect` feels like the wrong way to sync the `toDate` (departure date) field whenever the `fromDate` (arrival date) changes, as it's tied to a user interaction (when someone clicks and populates the date picker) and so the sync should be moved into the event handler imo. There's a `onPostChange` on the Datepicker component that would be suitable for the job!

(But also appreciate you may not want to change too much here for a small fix, so I let you decide if you want to make the change or not 🙂 )

**Review by darrenvong — COMMENTED** [review]
Sorry for the slow review - been busy over the last two weeks! 😅

**Comment by darrenvong** [comment]
Also @aapeliv is the preview broken whenever someone creates a PR from a branch? Would be nice to fix that so we don't always have to pull things down to run the app locally to review small changes... 🙏

File: features/profile/view/NewHostRequest.tsx (hunk 4 above)
Comment (bakeiro) [reply features/profile/view/NewHostRequest.tsx:129]: I prefer to not 🙃

**Comment by aapeliv** [comment]
> Also @aapeliv is the preview broken whenever someone creates a PR from a branch? Would be nice to fix that so we don't always have to pull things down to run the app locally to review small changes... 🙏

How was it set up back in the day? I guess on vercel?

I also feel like it might be good to merge the repos together, that way we could have a view of the whole thing in one place. At least I am completely out of the loop on the frontend repo.

**Comment by darrenvong** [comment]
> How was it set up back in the day? I guess on vercel?
> 
> I also feel like it might be good to merge the repos together, that way we could have a view of the whole thing in one place. At least I am completely out of the loop on the frontend repo.

Yeah it was on Vercel when we migrated the app to use Next.js, so that might be the easiest way to set things back up again. I should have permission to hook projects up against our Vercel account?

Considering the only reason we split this out was to allow things to deploy to k8 more easily (??), and we're not doing that anymore, I think I'm ok with bringing this back into the monorepo

File: features/profile/view/NewHostRequest.tsx (hunk 3 above)
Comment (bakeiro) [reply features/profile/view/NewHostRequest.tsx]: done!! ✅

**Review by darrenvong — APPROVED** [review]

**Review by bakeiro — COMMENTED** [review]
.
